-- //Creates whopipe video views table with four columns. 
-- //If not exists prevents the create table from being attempted if it already exists

CREATE TABLE IF NOT EXISTS whopipe_video_views (
    view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_name TEXT NOT NULL,
    region TEXT NOT NULL,
    date_viewed TIMESTAMP DEFAULT now() NOT NULL
);

-- Create a new type called department which is an enum. Enum is a list of options that may be used by columns (which have this new type) in table rows.

-- create type doesnt support if not exists so insted we remove the type if it exists first. 

DROP TYPE IF EXISTS department;
CREATE TYPE department AS ENUM (
    'Electronics',
    'Cleaning',
    'Grocery',
    'Furniture',
    'Stationery',
    'Clothing',
    'DIY',
    'Sports',
    'Homeware',
    'Games',
    'Transport'
);

-- Create a tabel called amazong_products with five columns. Two interesing are price and category. 

-- price is set to a decimal which can be 12 in 'prcision' and 2 decimal points. 
-- category has the type of department, which is the enum we created in the second transaction. Wnen we insert rows into the amazong_products table, the value for category would nee dot be one of those listed in the enum for department. 

CREATE TABLE IF NOT EXISTS amazong_products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    image TEXT,
    category department NOT NULL
);